### ISSUE TITLE
 .

### ISSUE THREAD

**Issue by lxcbetter** [John-Chen92/Electricity_Load_Forecast#2]

**Comment by John-Chen92** [comment]
这个实现没问题哈，你预算多少

**Comment by lxcbetter** [comment]
200可以吗，一个100



刘星辰
***@***.***







                       
Original
                       
                     

From:"ZhangChen"< ***@***.*** &gt;;

Date:2024/5/4 9:06

To:"John-Chen92/Electricity_Load_Forecast"< ***@***.*** &gt;;

CC:"Xingchen Liu"< ***@***.*** &gt;;"Author"< ***@***.*** &gt;;

Subject:Re: [John-Chen92/Electricity_Load_Forecast] 你好，能请你做个负荷预测吗。有偿 (Issue #2)




 
这个实现没问题哈，你预算多少

**Comment by John-Chen92** [comment]
可以哈

**Comment by lxcbetter** [comment]
那你加我个联系方式吧
qq:1270215484
wechat:wslxcsg



lxcbetter
***@***.***







                       
Original
                       
                     

From:"ZhangChen"< ***@***.*** &gt;;

Date:2024/5/4 9:09

To:"John-Chen92/Electricity_Load_Forecast"< ***@***.*** &gt;;

CC:"Xingchen Liu"< ***@***.*** &gt;;"Author"< ***@***.*** &gt;;

Subject:Re: [John-Chen92/Electricity_Load_Forecast] 你好，能请你做个负荷预测吗。有偿 (Issue #2)




 
可以哈

**Comment by lxcbetter** [comment]
> 可以哈

或者你给我一个你的联系方式吧，我加一下
